import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { ConfigStore, defaultConfig, relayEndpointId, validateConfig } from "../server/config-store.js";

test("defaults Relay Endpoint ID separately from the local route ID", () => {
  const config = defaultConfig();
  assert.equal(config.relay.endpointId, "");
  assert.match(config.relay.deviceId, /^host_/);
  assert.equal(relayEndpointId(config.relay), "");
  assert.equal(config.codex.appServerTransport, "stdio");
});

test("validates the shared Unix App Server transport", () => {
  const config = defaultConfig();
  config.codex.appServerTransport = "unix";
  config.codex.appServerSocket = "";
  assert.throws(() => validateConfig(config), /Unix Socket/);
  config.codex.appServerSocket = "/tmp/codex-app-server.sock";
  assert.doesNotThrow(() => validateConfig(config));
});

test("migrates a legacy manually assigned endpoint ID without replacing local routing", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-config-migrate-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  await fs.writeFile(path.join(configDir, "config.json"), JSON.stringify({
    version: 1,
    relay: { deviceId: "cli_legacy-endpoint", spaceId: "space-1" },
  }));
  const store = new ConfigStore({ configDir });
  await store.load();
  assert.equal(store.get().relay.endpointId, "cli_legacy-endpoint");
  assert.equal(store.get().relay.deviceId, "cli_legacy-endpoint");
});

test("does not migrate an autogenerated host ID into a Relay Endpoint ID", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-config-migrate-host-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  await fs.writeFile(path.join(configDir, "config.json"), JSON.stringify({
    version: 1,
    relay: { deviceId: "host_legacy-local-route", spaceId: "space-1" },
  }));
  const store = new ConfigStore({ configDir });
  await store.load();
  assert.equal(store.get().relay.endpointId, "");
  assert.equal(store.get().relay.deviceId, "host_legacy-local-route");
});

test("removes legacy shared App Server settings during config migration", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-config-managed-only-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  await fs.writeFile(path.join(configDir, "config.json"), JSON.stringify({
    version: 1,
    relay: { endpointId: "endpoint-1", spaceId: "space-1" },
    codex: {
      executable: "/usr/local/bin/codex",
      connectionMode: "shared",
      appServerEndpoint: "unix:///tmp/obsolete-codex.sock",
      autoStartAppServer: true,
      defaultWorkingDirectory: "",
    },
  }));
  const store = new ConfigStore({ configDir });
  await store.load();
  assert.equal(store.get().codex.connectionMode, undefined);
  assert.equal(store.get().codex.appServerEndpoint, undefined);
  const persisted = JSON.parse(await fs.readFile(path.join(configDir, "config.json"), "utf8"));
  assert.equal(persisted.codex.connectionMode, undefined);
  assert.equal(persisted.codex.appServerEndpoint, undefined);
});

test("configuration persists with owner-only permissions", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-config-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  const updated = await store.update({
    relay: { url: "ws://127.0.0.1:8787/v1/connect", spaceId: `test-${process.pid}` },
    allowedProjects: [path.resolve(configDir)],
  });

  assert.equal(updated.relay.spaceId, `test-${process.pid}`);
  assert.equal(updated.relay.tokenConfigured, false);
  const stat = await fs.stat(path.join(configDir, "config.json"));
  assert.equal(stat.mode & 0o777, 0o600);

  const reloaded = new ConfigStore({ configDir });
  await reloaded.load();
  assert.equal(reloaded.get().relay.url, "ws://127.0.0.1:8787/v1/connect");
});

test("relay token uses the cross-platform file store and is returned to the local dashboard", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-token-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();

  const updated = await store.update({ relay: { spaceId: "token-space" } }, "relay-token-value");
  assert.equal(updated.relay.token, undefined);
  assert.equal(updated.relay.tokenConfigured, true);

  const secretStat = await fs.stat(path.join(configDir, "secrets.json"));
  assert.equal(secretStat.mode & 0o777, 0o600);
  const reloaded = new ConfigStore({ configDir });
  await reloaded.load();
  assert.equal((await reloaded.publicConfig()).relay.token, undefined);
  assert.equal((await reloaded.publicConfig({ includeToken: true })).relay.token, "relay-token-value");

  const switched = await reloaded.update({ relay: { spaceId: "other-space" } });
  assert.equal(switched.relay.tokenConfigured, false);
});

test("relay credentials keep grant metadata isolated per Space", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await store.update({ relay: { url: "ws://127.0.0.1:8788/v1/connect", spaceId: "space-a" } }, {
    connectToken: "token-a",
    endpointGrant: "grant-a-0123456789",
    grantExpiresAt: Date.now() + 60_000,
    tokenEndpoint: "http://127.0.0.1:8788/api/connect-tokens/refresh",
  });
  const dashboard = await store.publicConfig({ includeToken: true });
  assert.equal(dashboard.relay.token, "token-a");
  assert.equal(dashboard.relay.endpointGrant, "grant-a-0123456789");
  assert.equal(dashboard.relay.endpointGrantConfigured, true);
  await store.update({}, { endpointGrant: '', grantExpiresAt: null, tokenEndpoint: '' });
  assert.equal((await store.relayCredential()).endpointGrant, undefined);
  assert.equal((await store.relayCredential()).tokenEndpoint, undefined);
  await store.update({ relay: { spaceId: "space-b" } });
  assert.equal((await store.relayCredential()), null);
});

test("partial credential updates preserve metadata and reset it when a credential rotates", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-partial-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  const tokenExpiry = Date.now() + 600_000;
  const grantExpiry = Date.now() + 86_400_000;
  await store.update({ relay: { spaceId: "partial-space" } }, {
    connectToken: "token-old",
    expiresAt: tokenExpiry,
    endpointGrant: "grant-old-0123456789",
    grantExpiresAt: grantExpiry,
  });

  await store.update({}, { connectToken: "token-old" });
  let credential = await store.relayCredential();
  assert.equal(credential.expiresAt, tokenExpiry);
  assert.equal(credential.endpointGrant, "grant-old-0123456789");
  assert.equal(credential.grantExpiresAt, grantExpiry);

  await store.update({}, { endpointGrant: "grant-new-0123456789" });
  credential = await store.relayCredential();
  assert.equal(credential.endpointGrant, "grant-new-0123456789");
  assert.equal(credential.grantExpiresAt, undefined);
  assert.equal(credential.expiresAt, tokenExpiry);
});

test("an empty partial credential update preserves the saved pairing", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-empty-patch-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await store.update({ relay: { spaceId: "empty-patch-space" } }, {
    connectToken: "empty-patch-token",
    endpointGrant: "empty-patch-grant-0123456789",
    expiresAt: Date.now() + 600_000,
    grantExpiresAt: Date.now() + 86_400_000,
  });

  await store.update({ relay: { deviceName: "renamed-host" } }, {});
  const credential = await store.relayCredential();
  assert.equal(credential.connectToken, "empty-patch-token");
  assert.equal(credential.endpointGrant, "empty-patch-grant-0123456789");
  assert.ok(credential.expiresAt > Date.now());
  assert.ok(credential.grantExpiresAt > Date.now());
});

test("undefined credential fields can clear a token, grant, and its metadata", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-undefined-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await store.update({ relay: { spaceId: "undefined-space" } }, {
    connectToken: "token-undefined",
    expiresAt: Date.now() + 600_000,
    endpointGrant: "grant-undefined-0123456789",
    grantExpiresAt: Date.now() + 86_400_000,
  });

  await store.update({}, { connectToken: undefined, expiresAt: undefined });
  let credential = await store.relayCredential();
  assert.equal(credential.connectToken, undefined);
  assert.equal(credential.expiresAt, undefined);
  assert.equal(credential.endpointGrant, "grant-undefined-0123456789");

  await store.update({}, {
    endpointGrant: undefined,
    grantExpiresAt: undefined,
    tokenEndpoint: undefined,
  });
  credential = await store.relayCredential();
  assert.equal(credential, null);
});

test("optional credential metadata can be cleared when no secret remains", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-metadata-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await store.update({ relay: { spaceId: "metadata-space" } }, {
    connectToken: "metadata-token",
  });
  await store.update({}, { connectToken: null, expiresAt: null, grantExpiresAt: null, tokenEndpoint: null });
  assert.equal(await store.relayCredential(), null);
});

test("environment token overrides keep the grant and return rotated credentials", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-env-"));
  t.after(async () => {
    delete process.env.CODEX_RELAY_TOKEN;
    await fs.rm(configDir, { recursive: true, force: true });
  });
  const store = new ConfigStore({ configDir });
  await store.load();
  await store.update({ relay: { spaceId: "env-space" } }, {
    connectToken: "persisted-token",
    expiresAt: Date.now() + 600_000,
    endpointGrant: "grant-env-0123456789",
    grantExpiresAt: Date.now() + 86_400_000,
  });
  process.env.CODEX_RELAY_TOKEN = "environment-token";

  const overridden = await store.relayCredential();
  assert.equal(overridden.connectToken, "environment-token");
  assert.equal(overridden.endpointGrant, "grant-env-0123456789");
  assert.equal(overridden.expiresAt, undefined);

  const rotated = await store.updateRelayCredential({
    connectToken: "rotated-token",
    expiresAt: Date.now() + 900_000,
  });
  assert.equal(rotated.connectToken, "rotated-token");
  assert.ok(rotated.expiresAt > Date.now());
  assert.equal(rotated.endpointGrant, "grant-env-0123456789");
});

test("rejects a refresh write when the Endpoint Grant was replaced", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-context-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await store.update({ relay: { spaceId: "context-space" } }, {
    connectToken: "token-before",
    endpointGrant: "grant-before-0123456789",
  });
  await store.update({}, { endpointGrant: "grant-after-0123456789" });

  const result = await store.updateRelayCredential({
    connectToken: "stale-refresh-token",
    expiresAt: Date.now() + 600_000,
  }, { endpointGrant: "grant-before-0123456789" });
  assert.equal(result, null);
  const credential = await store.relayCredential();
  assert.equal(credential.endpointGrant, "grant-after-0123456789");
  assert.equal(credential.connectToken, "token-before");
  assert.equal(credential.expiresAt, undefined);
});

test("relay credential rejects public HTTP refresh endpoints", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-credential-invalid-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await assert.rejects(
    () => store.update({ relay: { spaceId: "space" } }, {
      connectToken: "token-a",
      endpointGrant: "grant-a-0123456789",
      tokenEndpoint: "http://relay.example.com/api/connect-tokens/refresh",
    }),
    /https/,
  );
});

test("public relays require TLS and URL credentials are rejected", () => {
  const base = defaultConfig();
  base.relay.url = "ws://relay.example.com/v1/connect";
  base.relay.spaceId = "space";
  assert.throws(() => validateConfig(base), /wss:\/\//);
  assert.doesNotThrow(() => validateConfig({ ...base, relay: { ...base.relay, url: "wss://relay.example.com/v1/connect" } }));
  assert.throws(
    () => validateConfig({ ...base, relay: { ...base.relay, url: "wss://user:password@relay.example.com/v1/connect" } }),
    /用户名或密码/,
  );
  assert.throws(
    () => validateConfig({ ...base, relay: { ...base.relay, url: "wss://relay.example.com/ws" } }),
    /\/v1\/connect/,
  );
  assert.throws(
    () => validateConfig({ ...base, relay: { ...base.relay, url: "wss://relay.example.com/v1/connect?token=secret" } }),
    /query 或 hash/,
  );
  assert.throws(
    () => validateConfig({ ...base, relay: { ...base.relay, url: "wss://relay.example.com/v1/connect#token" } }),
    /query 或 hash/,
  );
});

test("validates Relay Endpoint ID when it is provided", () => {
  const base = defaultConfig();
  assert.doesNotThrow(() => validateConfig({ ...base, relay: { ...base.relay, endpointId: "cli_valid-01" } }));
  assert.throws(
    () => validateConfig({ ...base, relay: { ...base.relay, endpointId: "invalid endpoint" } }),
    /Relay Endpoint ID 无效/,
  );
});

test("configuration rejects type-confused permissions and relative working directories", async (t) => {
  const configDir = await fs.mkdtemp(path.join(os.tmpdir(), "codex-relay-config-invalid-"));
  t.after(() => fs.rm(configDir, { recursive: true, force: true }));
  const store = new ConfigStore({ configDir });
  await store.load();
  await assert.rejects(() => store.update({ permissions: { sendMessages: "false" } }), /必须是布尔值/);
  await assert.rejects(() => store.update({ codex: { defaultWorkingDirectory: "relative/path" } }), /必须是绝对路径/);
  await assert.rejects(() => store.update({}, { token: "not-a-string" }), /Relay Token/);
});
